/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.itsco;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 5;
  /** RegularExpression Id. */
  int FIN = 6;
  /** RegularExpression Id. */
  int VAR = 7;
  /** RegularExpression Id. */
  int ENTERO = 8;
  /** RegularExpression Id. */
  int CADENA = 9;
  /** RegularExpression Id. */
  int FLOTANTE = 10;
  /** RegularExpression Id. */
  int IMPRIMIR = 11;
  /** RegularExpression Id. */
  int LEER = 12;
  /** RegularExpression Id. */
  int SI = 13;
  /** RegularExpression Id. */
  int ENTONCES = 14;
  /** RegularExpression Id. */
  int SINO = 15;
  /** RegularExpression Id. */
  int PARA = 16;
  /** RegularExpression Id. */
  int HASTA = 17;
  /** RegularExpression Id. */
  int SIGUIENTE = 18;
  /** RegularExpression Id. */
  int MIENTRAS = 19;
  /** RegularExpression Id. */
  int HACER = 20;
  /** RegularExpression Id. */
  int SUMA = 21;
  /** RegularExpression Id. */
  int RESTA = 22;
  /** RegularExpression Id. */
  int MULT = 23;
  /** RegularExpression Id. */
  int DIV = 24;
  /** RegularExpression Id. */
  int MOD = 25;
  /** RegularExpression Id. */
  int POT = 26;
  /** RegularExpression Id. */
  int MAYOR = 27;
  /** RegularExpression Id. */
  int MENOR = 28;
  /** RegularExpression Id. */
  int IGUAL = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int AP = 33;
  /** RegularExpression Id. */
  int CP = 34;
  /** RegularExpression Id. */
  int digito = 35;
  /** RegularExpression Id. */
  int letra = 36;
  /** RegularExpression Id. */
  int VALOR_ENTERO = 37;
  /** RegularExpression Id. */
  int VALOR_FLOTANTE = 38;
  /** RegularExpression Id. */
  int VALOR_CADENA = 39;
  /** RegularExpression Id. */
  int ID = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Inicio\"",
    "\"Fin\"",
    "\"var\"",
    "\"int\"",
    "\"string\"",
    "\"float\"",
    "\"Imprimir\"",
    "\"Leer\"",
    "\"If\"",
    "\":\"",
    "\"Else\"",
    "\"Para\"",
    "\"Hasta\"",
    "\"Sig\"",
    "\"While\"",
    "\"Do\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "<digito>",
    "<letra>",
    "<VALOR_ENTERO>",
    "<VALOR_FLOTANTE>",
    "<VALOR_CADENA>",
    "<ID>",
  };

}
